import { FacilityItem } from '../../views/facility/ItemModal';

export const FacilityData: FacilityItem[] = [
  {
    numbering: 1,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
    details: [
      { date: '2022.03.22', hour: 4, amount: 3, effort: 12 },
      { date: '2022.05.20', hour: 3, amount: 2, effort: 15 },
      { date: '2022.03.22', hour: 5, amount: 5, effort: 10 },
      { date: '2022.03.22', hour: 5, amount: 5, effort: 10 },
    ],
  },
  {
    numbering: 2,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/ctest.jpg',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 3,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 4,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 5,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 6,
    district: '부산',
    title: '부산국립해양대학교 진입로 방파재',
    img: 'item1.jpg',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 7,
    district: '기장군',
    title: '부산국립해양대학교 진입로 방파재',
    img: '/logo192.png',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
  {
    numbering: 8,
    district: '기장군',
    title: '부산국립해양대학교 진입로 방파재',
    img: 'item1.jpg',
    location: '영도구 해양로 435',
    dimension: '길이 590m / 폭 9m',
    status: 'E',
  },
];

export const LabData = [
  {
    id: '1',
    selected: false,
    numbering: 1,
    title: '공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사항 입니다. 공지사',
    author: '관리자 1',
    date: '2023-05-05',
    body: '글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기글쓰기.',
  },
  { id: '2', selected: false, numbering: 2, title: 'Short', author: '관리자 2', date: '2023-05-05', body: '' },
  { id: '3', selected: false, numbering: 3, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '4', selected: false, numbering: 4, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '5', selected: false, numbering: 5, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '6', selected: false, numbering: 6, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '7', selected: false, numbering: 7, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '8', selected: false, numbering: 8, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '9', selected: false, numbering: 9, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '10', selected: false, numbering: 10, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '11', selected: false, numbering: 11, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
  { id: '12', selected: false, numbering: 12, title: 'Short', author: '관리자 1', date: '2023-05-05', body: '' },
];

export const UserManagementData = [
  {
    id: '1',
    selected: false,
    name: '홍길동',
    numbering: 1,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '2',
    selected: false,
    name: '홍길동',
    numbering: 2,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '3',
    selected: false,
    name: '홍길동',
    numbering: 3,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '4',
    selected: false,
    name: '홍길동',
    numbering: 4,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '5',
    selected: false,
    name: '홍길동',
    numbering: 5,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '6',
    selected: false,
    name: '홍길동',
    numbering: 6,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '7',
    selected: false,
    name: '홍길동',
    numbering: 7,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '8',
    selected: false,
    name: '홍길동',
    numbering: 8,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '9',
    selected: false,
    name: '홍길동',
    numbering: 9,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '10',
    selected: false,
    name: '홍길동',
    numbering: 10,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '11',
    selected: false,
    name: '홍길동',
    numbering: 11,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
  {
    id: '12',
    selected: false,
    name: '홍길동',
    numbering: 12,
    username: 'hong222',
    password: 'pw231122',
    email: 'email@gmail.com',
    phone: '010-5555-8888',
  },
];
